menu:
  Home: /
  Archives: /archives

# AddToAny Share. See: https://www.addtoany.com
addtoany:
  enable: false
  buttons:
    - facebook
    - twitter

facebook:
twitter:
github: huazie

fancybox: true
google_analytics:
rss: /atom.xml
# Display a "Read More" link under each post's excerpt in /archives page
#excerpt_link: 'Read More'

disqus_shortname:

comments:
  style: tabs
  active: utterances
  lazyload: true
  nav:
    utterances:
      text: Utterances
      order: 1
    gitalk:
      text: Gitalk
      order: 2
    giscus:
      text: Giscus
      order: 3

utterances:
  enable: true
  repo: huazie/hexo-theme-diversity 
  issue_term: pathname
  theme: github-light
  dark: icy-dark

gitalk:
  enable: true
  github_id: huazie
  repo: hexo-theme-diversity
  client_id: Ov23liUeEbTbvL4TtFLI
  client_secret: 625f6af43748eb4a6a27a9111d252155e88c836e
  admin_user: huazie
  distraction_free_mode: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token

giscus:
  enable: true
  repo: huazie/hexo-theme-diversity
  repo_id: R_kgDOLxZw-w
  category: Announcements
  category_id: DIC_kwDOLxZw-84CiJXv
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  theme: light
  dark: dark
  input_position: top