# ===============
# Header
# ===============
# Navigation menu
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
# RSS link
rss: /atom.xml
# Path of title banner image of page top
banner: "images/banner.jpg"
# Subtitle of page top
subtitle:
# Header links with icon, specified links will appear at the top right corner of the page
# Each name must correspond to the icon name of Fork Awesome
# https://forkaweso.me/Fork-Awesome/icons/
links: 
   github: https://github.com/huazie
#  twitter: https://twitter.com/your_twitter_account
#  telegram: https://t.me/your_telegram_account

# ===============
# Content
# ===============
# "Read More" link at the bottom of excerpted articles. `false` to hide the link.
excerpt_link: Read More
# Enable fancybox
fancybox: true

# ===============
# Footer
# ===============
# Display copyright notice in footer. Please see https://creativecommons.org/choose/ and https://choosealicense.com/
# You can use html like below.
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>
copyright:

# ===============
# Sidebar
# ===============
# Sidebar style. You can choose `left`, `right`, `bottom` or `false`.
sidebar: left
# Widgets displaying in sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# ===============
# Widget behavior
# ===============
archive_type: 'monthly'
show_count: false
# How many posts display in Home page.
recent_posts_limits: 5

# ===============
# Miscellaneous
# ===============
# Google Analytics ID
google_analytics:
gauges_analytics:
# Favicon path
favicon: /favicon.png
# Twitter ID
twitter:
fb_admins:
fb_app_id:

# ===============
# Comment system
# ===============
# Disqus comment system.
disqus_shortname:
# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info

comments:
  style: tabs
  active: utterances
  lazyload: true
  nav:
    utterances:
      text: Utterances
      order: 1
    gitalk:
      text: Gitalk
      order: 2
    giscus:
      text: Giscus
      order: 3
    twikoo:
      text: Twikoo
      order: 4
    gitment:
      text: Gitment
      order: 5

utterances:
  enable: true
  repo: huazie/hexo-theme-diversity 
  issue_term: pathname
  theme: github-light
  dark: github-dark

gitalk:
  enable: true
  github_id: huazie
  repo: hexo-theme-diversity
  client_id: Ov23liUeEbTbvL4TtFLI
  client_secret: 625f6af43748eb4a6a27a9111d252155e88c836e
  admin_user: huazie
  distraction_free_mode: true
  proxy: https://huazie-oauth.netlify.app/api/auth

giscus:
  enable: true
  repo: huazie/hexo-theme-diversity
  repo_id: R_kgDOLxZw-w
  category: Announcements
  category_id: DIC_kwDOLxZw-84CiJXv
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  theme: light
  dark: dark
  input_position: top

twikoo:
  enable: true
  env_id: https://huazie.netlify.app/.netlify/functions/twikoo

gitment:
  enable: true
  owner: huazie
  repo: hexo-theme-diversity
  client_id: Ov23li7WIKTIa0F9GJtZ
  client_secret: 7f068a3fa7852d2ded8742833939eac385d957b6
  #proxy: http://localhost:8888/api/auth
  proxy: https://huazie-oauth.netlify.app/api/auth