name: Build And Deploy

on:
  push:
    branches:
      - main # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Checkout Theme Diversity
        uses: actions/checkout@v4
        with:
          repository: huazie/hexo-theme-diversity
          path: themes/diversity
      - name: Checkout Theme Phase
        uses: actions/checkout@v4
        with:
          repository: huazie/hexo-theme-phase
          path: themes/phase
      - name: Checkout Theme Light
        uses: actions/checkout@v4
        with:
          repository: hexojs/hexo-theme-light
          path: themes/light
      - name: Checkout Theme Next
        uses: actions/checkout@v4
        with:
          repository: next-theme/hexo-theme-next
          path: themes/next
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Clean
        run: npm run clean
      - name: Build
        run: npm run build
      - name: Clean existing game directory
        run: rm -rf public/diversity/game
      - name: Checkout Game
        uses: actions/checkout@v4
        with:
          repository: huazie/flea-game
          path: public/diversity/game
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4